### ISSUE TITLE
Read PT token from ENV

### ISSUE THREAD

**Issue by tadejm** [mezis/git-whistles#34]
Many of us have `.gitconfig` committed and pushed in the dotfiles public repo on GitHub.

Myself I store sensitive keys in a `.private` file which is ignored by git that get's sources when the env loads.

In order to prevent PT token leaking my suggestion is to check if `PIVOTAL_TOKEN` env variable exists and take that as a precedence over `git config pivotal-tracker.token`.

Thoughts?

**Comment by pedrocunha** [comment]
Hey @tadejm I'll close this for now. Feel free to open this again if you make any progress / contribute to it. Thank you.
