### ISSUE TITLE
[git-pull-request] Pivotal Tracker story is too big - Github returns 414

### ISSUE THREAD

**Issue by Davidslv** [mezis/git-whistles#38]
Hello, 

I've just discovered that when git-whistles tries to parse the story content and send it through the url params, if it's too big then github throws a 414 - URI too large.

![screen shot 2015-03-25 at 12 01 58](https://cloud.githubusercontent.com/assets/136777/6824126/f919f7be-d2e6-11e4-96b4-7c4760966404.png)

Maybe a good solution will be to truncate the story after a certain amount of characters?

David

**Comment by pedrocunha** [comment]
Will fix

**Comment by mezis** [comment]
Good idea. Never bumped into it yet ;)
