### ISSUE TITLE
problems with installing git-whistles

### ISSUE THREAD

**Issue by max-l** [mezis/git-whistles#44]
I had problems installing git-whistles, and when I try to merge a branch with PO conflicts, I get : 

/usr/local/bin/git-merge-po:23:in `load': cannot load such file -- /var/lib/gems/1.9.1/gems/git-whistles-0.12.0/bin/git-merge-po (LoadError)
	from /usr/local/bin/git-merge-po:23:in `<main>'

Here is the output of the installation process : 

>sudo gem install git-whistles

Building native extensions.  This could take a while...
Fetching: nokogiri-happymapper-0.5.9.gem (100%)
Fetching: builder-3.2.2.gem (100%)
Fetching: safe_yaml-1.0.4.gem (100%)
Fetching: crack-0.4.2.gem (100%)
Fetching: unf_ext-0.0.7.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: unf-0.1.4.gem (100%)
Fetching: domain_name-0.5.24.gem (100%)
Fetching: http-cookie-1.0.2.gem (100%)
Fetching: mime-types-2.6.1.gem (100%)
Fetching: netrc-0.10.3.gem (100%)
Fetching: rest-client-1.8.0.gem (100%)
Fetching: pivotal-tracker-0.5.13.gem (100%)
Fetching: tins-1.6.0.gem (100%)
Fetching: term-ansicolor-1.3.2.gem (100%)
Fetching: git-whistles-0.12.0.gem (100%)
Successfully installed nokogiri-1.6.6.2
Successfully installed nokogiri-happymapper-0.5.9
Successfully installed builder-3.2.2
Successfully installed safe_yaml-1.0.4
Successfully installed crack-0.4.2
Successfully installed unf_ext-0.0.7.1
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.24
Successfully installed http-cookie-1.0.2
Successfully installed mime-types-2.6.1
Successfully installed netrc-0.10.3
Successfully installed rest-client-1.8.0
Successfully installed pivotal-tracker-0.5.13
Successfully installed tins-1.6.0
Successfully installed term-ansicolor-1.3.2
Successfully installed git-whistles-0.12.0
16 gems installed
Installing ri documentation for nokogiri-1.6.6.2...
Installing ri documentation for nokogiri-happymapper-0.5.9...
Installing ri documentation for builder-3.2.2...
Installing ri documentation for safe_yaml-1.0.4...
Installing ri documentation for crack-0.4.2...
Installing ri documentation for unf_ext-0.0.7.1...
Installing ri documentation for unf-0.1.4...
Installing ri documentation for domain_name-0.5.24...
Installing ri documentation for http-cookie-1.0.2...
Installing ri documentation for mime-types-2.6.1...
Installing ri documentation for netrc-0.10.3...
Installing ri documentation for rest-client-1.8.0...
Installing ri documentation for pivotal-tracker-0.5.13...
Installing ri documentation for tins-1.6.0...

RDoc::Parser::Ruby failure around line 4 of
lib/tins/method_description.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/bin/ruby1.9.1 -c lib/tins/method_description.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(RDoc::Error) unknown type of %string "i"

ERROR:  While generating documentation for tins-1.6.0
... MESSAGE:   unknown type of %string "i"
... RDOC args: --ri --op /var/lib/gems/1.9.1/doc/tins-1.6.0/ri --title Tins - Useful stuff. --main README.md lib README.md lib/dslkit.rb lib/dslkit/polite.rb lib/dslkit/rude.rb lib/spruz.rb lib/tins.rb lib/tins/alias.rb lib/tins/annotate.rb lib/tins/ask_and_send.rb lib/tins/attempt.rb lib/tins/bijection.rb lib/tins/case_predicate.rb lib/tins/complete.rb lib/tins/concern.rb lib/tins/count_by.rb lib/tins/date_dummy.rb lib/tins/date_time_dummy.rb lib/tins/deep_const_get.rb lib/tins/deep_dup.rb lib/tins/dslkit.rb lib/tins/extract_last_argument_options.rb lib/tins/file_binary.rb lib/tins/find.rb lib/tins/generator.rb lib/tins/go.rb lib/tins/hash_symbolize_keys_recursive.rb lib/tins/hash_union.rb lib/tins/if_predicate.rb lib/tins/implement.rb lib/tins/limited.rb lib/tins/lines_file.rb lib/tins/memoize.rb lib/tins/method_description.rb lib/tins/minimize.rb lib/tins/module_group.rb lib/tins/named_set.rb lib/tins/null.rb lib/tins/once.rb lib/tins/p.rb lib/tins/partial_application.rb lib/tins/proc_compose.rb lib/tins/proc_prelude.rb lib/tins/range_plus.rb lib/tins/require_maybe.rb lib/tins/responding.rb lib/tins/rotate.rb lib/tins/secure_write.rb lib/tins/sexy_singleton.rb lib/tins/shuffle.rb lib/tins/string_byte_order_mark.rb lib/tins/string_camelize.rb lib/tins/string_underscore.rb lib/tins/string_version.rb lib/tins/subhash.rb lib/tins/terminal.rb lib/tins/thread_local.rb lib/tins/time_dummy.rb lib/tins/to.rb lib/tins/to_proc.rb lib/tins/token.rb lib/tins/uniq_by.rb lib/tins/version.rb lib/tins/write.rb lib/tins/xt.rb lib/tins/xt/annotate.rb lib/tins/xt/ask_and_send.rb lib/tins/xt/attempt.rb lib/tins/xt/blank.rb lib/tins/xt/case_predicate.rb lib/tins/xt/complete.rb lib/tins/xt/concern.rb lib/tins/xt/count_by.rb lib/tins/xt/date_dummy.rb lib/tins/xt/date_time_dummy.rb lib/tins/xt/deep_const_get.rb lib/tins/xt/deep_dup.rb lib/tins/xt/dslkit.rb lib/tins/xt/extract_last_argument_options.rb lib/tins/xt/file_binary.rb lib/tins/xt/full.rb lib/tins/xt/hash_symbolize_keys_recursive.rb lib/tins/xt/hash_union.rb lib/tins/xt/if_predicate.rb lib/tins/xt/implement.rb lib/tins/xt/irb.rb lib/tins/xt/method_description.rb lib/tins/xt/named.rb lib/tins/xt/null.rb lib/tins/xt/p.rb lib/tins/xt/partial_application.rb lib/tins/xt/proc_compose.rb lib/tins/xt/proc_prelude.rb lib/tins/xt/range_plus.rb lib/tins/xt/require_maybe.rb lib/tins/xt/responding.rb lib/tins/xt/rotate.rb lib/tins/xt/secure_write.rb lib/tins/xt/sexy_singleton.rb lib/tins/xt/shuffle.rb lib/tins/xt/string.rb lib/tins/xt/string_byte_order_mark.rb lib/tins/xt/string_camelize.rb lib/tins/xt/string_underscore.rb lib/tins/xt/string_version.rb lib/tins/xt/subhash.rb lib/tins/xt/symbol_to_proc.rb lib/tins/xt/time_dummy.rb lib/tins/xt/time_freezer.rb lib/tins/xt/to.rb lib/tins/xt/uniq_by.rb lib/tins/xt/write.rb --title tins-1.6.0 Documentation --quiet

**Comment by pedrocunha** [comment]
Hi Max,

Does the same problem occur on different versions of ruby or just for ruby 1.9.1 ? 

What is your gem setup ? Machine default, RVM, rbenv or other setup ?

**Comment by max-l** [comment]
I haven't tried other versions of ruby, 
I tried this instead : https://github.com/beck/git-po-merge
and it worked, given my current time constraints I will stick with that for the moment.

I'm not so familiar with Ruby, I tend to always run into "dependency hell" with ruby tools, it reminds me of Scala ;-)

Sorry for the disturbance,  let me know if there's a way I can produce a dump of my env to help figure out what's wrong...

**Comment by pedrocunha** [comment]
Hi Max, sorry for delay in response, can you just confirm me that you are using ruby 1.9.1? What is the output of `ruby -v` in your system ?

> I'm not so familiar with Ruby, I tend to always run into "dependency hell" with ruby tools, it reminds me of Scala ;-)

Aha ! Good point ! You are probably just using ruby on its own, however the rails ecosystem has brought some nice tools to solve this. (Examples: rbenv, RVM and Bundler, etc.. - p.s. you don't need to be using Rails to make use of this..)

However I'm afraid ruby versions up to 1.9.3 have stopped receiving security updates - [source](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/). I would strongly advise to upgrade as soon as possible.

**Comment by pedrocunha** [comment]
@max-l I will close this for now, please feel free to open this again if you face any new issues. Thanks
