### ISSUE TITLE
Gem does not build on Rubygems 2.5.X with certain versions of Ruby

### ISSUE THREAD

**Issue by pedrocunha** [mezis/git-whistles#48]
If I try to install git-whistles under ruby 2.3.0 (pristine machine) I get the following error:

```
ERROR:  While executing gem ... (Gem::Package::PathError)`
```

@martyphee does also get the same problem when installing the gem under 2.2.3. I can't replicate that.

After some investigation looks like the culprit is the latest RubyGems version 2.5. This is the offending PR: https://github.com/rubygems/rubygems/pull/1209 which broke the support of symlinks in the gem files. 

For now it doesn't seem a problem that be solved in git-whistles and **the solution is to downgrade ruby gems. I've tried with 2.4.8 and works fine.**

**Comment by pedrocunha** [comment]
\cc @martyphee

**Comment by pedrocunha** [comment]
Issue on ruby gems: https://github.com/rubygems/rubygems/issues/1448

**Comment by pedrocunha** [comment]
Managed to fix the problem by compiling the gem under ruby 2.2.4. I've pushed to rubygems git-whistles 1.0.2 which I've confirmed locally that does install correctly on ruby 2.3.

**Comment by martyphee** [comment]
Looks go to me!  I'll try to get the PR creator this week.
