### ISSUE TITLE
All commands don't install correctly with 2.1.8 or 2.2.2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by vwal** [mezis/git-whistles#52]
When I try to install git-whistles on a newly (and correctly :-) installed Ruby 2.1.8 or 2.2.2 on Ubuntu 14.04 using `gem install git-whistles`, the scripts from the libexec directory don't get linked anywhere, and so `git-chop`, `git-list-branches`, `git-merge-po`, and `git-stash-and-checkout` won't be accessible without manual intervention (i.e. without symlinking them to someplace on the path, such as to the current ruby's bin directory).

The following error also shows up, but executing `gem pristine` as suggested doesn't do any good:

    /usr/local/rvm/gems/ruby-2.1.8/gems/git-whistles-1.1.0/bin/git-chop maybe `gem pristine git-whistles` will fix it?
    /usr/local/rvm/gems/ruby-2.1.8/gems/git-whistles-1.1.0/bin/git-list-branches maybe `gem pristine git-whistles` will fix it?
    /usr/local/rvm/gems/ruby-2.1.8/gems/git-whistles-1.1.0/bin/git-merge-po maybe `gem pristine git-whistles` will fix it?
    /usr/local/rvm/gems/ruby-2.1.8/gems/git-whistles-1.1.0/bin/git-stash-and-checkout maybe `gem pristine git-whistles` will fix it?

.. and, in fact, the mentioned scripts are not present in the mentioned directory (only in ../libexec).

**Comment by pedrocunha** [comment]
Hey @vwal which rubygems version are you using?

**Comment by vwal** [comment]
@pedrocunha It's 2.4.8.

**Comment by pedrocunha** [comment]
I think they have fixed recently problems with symlinks, can you try updating to the latest and reinstalling the gem please?

Currently my system:
```
> gem -v
2.6.2
```

**Comment by vwal** [comment]
Yes, that did it, thank you! I haven't used Ruby much, so I didn't think of needing to updating rubygems. I applied:

    gem install rubygems-update
    update_rubygems
    gem update --system

.. and then uninstalled/reinstalled git-whistles, and now it's working without problems.

**Comment by pedrocunha** [comment]
Great! Glad to know all it is good
