### ISSUE TITLE
On Ubuntu 16.04 it fails to install...

### ISSUE THREAD

**Issue by ciampix** [mezis/git-whistles#58]
When installing it does this:

#gem install git-whistles

Fetching: git-whistles-1.1.3.gem (100%)

/var/lib/gems/2.3.0/gems/git-whistles-1.1.3/bin/git-chop maybe `gem pristine git-whistles` will fix it?

/var/lib/gems/2.3.0/gems/git-whistles-1.1.3/bin/git-list-branches maybe `gem pristine git-whistles` will fix it?
/var/lib/gems/2.3.0/gems/git-whistles-1.1.3/bin/git-merge-po maybe `gem pristine git-whistles` will fix it?

/var/lib/gems/2.3.0/gems/git-whistles-1.1.3/bin/git-stash-and-checkout maybe `gem pristine git-whistles` will fix it?

Successfully installed git-whistles-1.1.3

Parsing documentation for git-whistles-1.1.3

Installing ri documentation for git-whistles-1.1.3

Done installing documentation for git-whistles after 0 seconds

1 gem installed`

the result is 4 links wrong, see:

ls -l /var/lib/gems/2.3.0/gems/git-whistles-1.1.3/bin/

lrwxrwxrwx 1 root root   56 set 27 10:30 git-chop -> /var/lib/gems/2.3.0/gems/git-whistles-1.1.3/git-whistles
-rwxr-xr-x 1 root root 2056 set 27 10:30 git-explore
-rwxr-xr-x 1 root root 3435 set 27 10:30 git-ff-all-branches
-rwxr-xr-x 1 root root 2928 set 27 10:30 git-jira-branch
-rwxr-xr-x 1 root root 4563 set 27 10:30 git-jira-pr
-rwxr-xr-x 1 root root 1505 set 27 10:30 git-latest-pushes
lrwxrwxrwx 1 root root   56 set 27 10:30 git-list-branches -> /var/lib/gems/2.3.0/gems/git-whistles-1.1.3/git-whistles
lrwxrwxrwx 1 root root   56 set 27 10:30 git-merge-po -> /var/lib/gems/2.3.0/gems/git-whistles-1.1.3/git-whistles
-rwxr-xr-x 1 root root 1382 set 27 10:30 git-outstanding-features
-rwxr-xr-x 1 root root 2782 set 27 10:30 git-pivotal-branch
-rwxr-xr-x 1 root root 1923 set 27 10:30 git-pivotal-open
-rwxr-xr-x 1 root root 4909 set 27 10:30 git-pivotal-pr
-rwxr-xr-x 1 root root 3115 set 27 10:30 git-select
lrwxrwxrwx 1 root root   56 set 27 10:30 git-stash-and-checkout -> /var/lib/gems/2.3.0/gems/git-whistles-1.1.3/git-whistles
-rwxr-xr-x 1 root root  255 set 27 10:30 git-whistles

since /var/lib/gems/2.3.0/gems/git-whistles-1.1.3/git-whistles does not exist...

running git (after the suggested .gitconfig addinng) does this:

git merge-po
git: 'merge-po' is not a git command. See 'git --help'.

BTW running `gem pristine git-whistles` does not fix it...

**Comment by pedrocunha** [comment]
Hi @ciampix, I think the issue might have to do with your rubygems version. Could you try `gem update --system` and then giving it another go?

**Comment by ciampix** [comment]
Uau! It worked, thanks!!!

**Comment by ciampix** [comment]
It correctly say:

 git merge-po
trap: ERR: bad trap

:+1:
